### ISSUE TITLE
chore: add missing license headers

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/managed-simple-data-exchanger-frontend#21]
Please add the license header to the following files according to the [TRG](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02):

- Dockerfile
- env.sh
- package.json
- public/env-config.js
- public/manifest.json
- src/assets/locales/de/main.json
- src/assets/locales/en/main.json
- src/components/NoDataPlaceholder.tsx
- src/components/dialogs/UsagePolicies.tsx
- src/components/sidebar/CollapseMenuItem.tsx
- src/components/sidebar/MenuHeading.tsx
- src/components/sidebar/MenuItem.tsx
- src/features/provider/policies/apiSlice.ts
- src/tests/__snapshots__/App.test.tsx.snap
- tsconfig.json

**Comment by ajithsimons** [comment]
@almadigabor json file won't allow comments inside. So license headers can't be added there. Rest all take care of already.
