### ISSUE TITLE
feat: add about page to the frontend application

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/managed-simple-data-exchanger-frontend#28]
[In this TRG](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-06#frontend-components) you can find a description that for frontend applications you need an About page that contains the following information. Make sure that your url's point to the exact tag or commit your release was built from like

- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/2.0.9/NOTICE.md
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/NOTICE.md

 Above you see that we don't accept if the url that points to the main branch but to the tag 2.0.9 (you need to change this for each release probably dynamically)

 Example About page:

[Your product name](URL to the YOUR repository)
* License: Apache-2.0
* License Path: <URL to the Apache License in your repository (*)>
* NOTICE: <URL to the NOTICE file in your repository (*)>
* Source URL: <URL to the your repository (*)>
* Commit ID: <the commit id the component delivery has been created / build from>

**Comment by adityagajbhiye9** [comment]
about page added.

**Comment by ajithsimons** [comment]
About page contents are dynamic now.
