### ISSUE TITLE
{TRG 7.02] Missing license and copyright header

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/managed-simple-data-exchanger-frontend#40]
(At least*) two of your files are missing the required license and copyright headers:
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/public/index.html
- https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/public/silent-check-sso.html

* have not checked each and every one - just some random sampling

@adityagajbhiye9 @sachinargade123 can you please check

**Comment by adityagajbhiye9** [comment]
copyright headers doesn't work for html files.
@ajithsimons  Please confirm.

**Comment by ajithsimons** [comment]
@hzierer  fixed it here -> https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/pull/38/commits/96ebdf2c7e0125373526d2fa3891a52a6b662d66 

Will be resolved once the PR is merged.

**Comment by hzierer** [comment]
Done. PR https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/pull/45 has been merged
