### ISSUE TITLE
[TRG 7.05] Missing legal decuments in Docker image

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/managed-simple-data-exchanger-frontend#41]
Hi @adityagajbhiye9,

the frontend docker image is missing the [legal information for distribution](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05#description). Can you please update your Dockerfile accordingly.

**Comment by adityagajbhiye9** [comment]
@hzierer  We have included in README.MD(https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/blob/main/README.md)
Please let us know any concern.

**Comment by adityagajbhiye9** [comment]
Added legal documents for docker image.

**Comment by adityagajbhiye9** [comment]
@hzierer Added copy cmd  for legal files in dockerfile.

**Comment by hzierer** [comment]
Done. Issue fixed with https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/commit/84b81855e8aa72618ad7b9f7b12004bc63e0a4c7
